### ISSUE TITLE
cannot read property style of null

### ISSUE THREAD

**Issue by tungs0ul** [iPzard/electron-react-python-template#13]
`<--- Last few GCs --->

[11060:000002953280E230]    38599 ms: Mark-sweep (reduce) 2041.2 (2050.9) -> 2040.7 (2052.6) MB, 1751.5 / 0.0 ms  (average mu = 0.123, current mu = 0.003) allocation failure scavenge might not succeed
[11060:000002953280E230]    40332 ms: Mark-sweep (reduce) 2041.8 (2054.6) -> 2041.4 (2055.1) MB, 1728.5 / 0.0 ms  (average mu = 0.067, current mu = 0.003) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF655CC046F napi_wrap+109311
 2: 00007FF655C65156 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+33302
 3: 00007FF655C65F26 node::OnFatalError+294
 4: 00007FF656532B4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF65651792D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6563C1CCC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6563CD04A v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF6563CA1F9 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF6563BEDE1 v8::internal::Heap::CollectGarbage+2033
10: 00007FF6563BD005 v8::internal::Heap::AllocateExternalBackingStore+1317
11: 00007FF6563DD2A7 v8::internal::Factory::NewFillerObject+183
12: 00007FF65610CC31 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF6565BB50D v8::internal::SetupIsolateDelegate::SetupHeap+463949
14: 00007FF6565BC3BD v8::internal::SetupIsolateDelegate::SetupHeap+467709
15: 00007FF65660B939 v8::internal::SetupIsolateDelegate::SetupHeap+792697
16: 00007FF6565AC302 v8::internal::SetupIsolateDelegate::SetupHeap+401986
17: 0000017D3033181C
(node:6432) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1545)
    at electron/js2c/renderer_init.js:115:431
    at electron/js2c/renderer_init.js:99:361
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:103:872)
    at EventEmitter.emit (events.js:310:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:818)
(node:6432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6432:0408/104410.334:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'instance' of undefined", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@6fd22580490b38d807360c16e10721d57779a6f0/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)
`
when I run
`npm start`
sometimes it runs, sometimes it shows the error
is that because of not enough memory ?  and how can I increase max memory ?

**Comment by iPzard** [comment]
You may have a promise that isn't handling potential errors with catch(), what steps do you take that lead to this error?

**Comment by iPzard** [comment]
I notice you're using NPM, but the yarn.lock file is checked, are you removing the yarn.lock file before running `npm install`?

Might remove the lock file and add to `.gitignore` to make the project more packager-agnostic.

**Comment by iPzard** [comment]
I think this may be related to an issue with the way things were setup in main.js. I've made some updates to the project which should resolve this. Feel free to re-open or create a new ticket if you continue to run into the problem.

**Comment by fetahokey** [comment]
@iPzard 

> Make sure your script is in a document ready handler - if you're trying to do things with the DOM before it's fully loaded, the DOM elements might not be available when you try to select them. – 

  ```
// Set opacity for title on window blur & focus
  const setTitleOpacity = (value) => `
    document.getElementById('electron-window-title-text').style.opacity = ${value};
    document.getElementById('electron-window-title-buttons').style.opacity = ${value};
```

**Comment by iPzard** [comment]
@fetahokey this is a good catch, thanks! That's probably where the style error was coming from. I've updated the code to look like the following and pushed it to the repo just now. 

` const setTitleOpacity = (value) => `
    if(document.readyState === 'complete') {
      document.getElementById('electron-window-title-text').style.opacity = ${value};
      document.getElementById('electron-window-title-buttons').style.opacity = ${value};
    }
  `;`
