### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by youngtype** [iPzard/electron-react-python-template#17]
![image](https://user-images.githubusercontent.com/79363260/116958336-e31dea00-aca2-11eb-8341-ce925ac9de76.png)

**Comment by youngtype** [comment]
![image](https://user-images.githubusercontent.com/79363260/116958664-07c69180-aca4-11eb-852c-d8db8cee595d.png)

**Comment by iPzard** [comment]
Hey @youngtype, the `get` method in `[src/utils/requests.js](https://github.com/iPzard/electron-react-python-template/blob/master/src/utils/requests.js)` takes a callback and error callback function. Here's the JSDoc info above that method for more info. 

/**
* @description - Helper GET method for sending requests to and from the Python/Flask services.
* @param {string} route - Path of the Python/Flask service you want to use.
* @param {Function} callback - Callback function which uses the returned data as an argument.
* @return response data from Python/Flask service.
* @memberof Requests
*/

If you're still having trouble after looking at that, do you mind if I see the code you're using the `get` method?

**Comment by iPzard** [comment]
Ah, you figured it out while I was typing that it appears, awesome! Let me know if anything else comes up.
