### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by youngtype** [iPzard/electron-react-python-template#18]
![Снимок экрана 2021-05-04 112504](https://user-images.githubusercontent.com/79363260/116977688-67846300-accb-11eb-98e4-9b29a31ce4be.png)

Hello, what causes this error and is it possible to connect electron windows-installer (squirrel.windows) here?

**Comment by iPzard** [comment]
Hello, I can help you track this down.. what steps did you take before getting that error? For example, did you run a script? If so, which script did you run?

**Comment by youngtype** [comment]
> Hello, I can help you track this down.. what steps did you take before getting that error? For example, did you run a script? If so, which script did you run?

Just pip3 install -r requirements.txt, then yarn install and yarn run build:package:windows

I have Python 3.7 I also have an error when building "pyinstaller" is not internal or external, thats it

**Comment by iPzard** [comment]
Ok thanks. I'll try to reproduce and update here.

**Comment by youngtype** [comment]
> Ok thanks. I'll try to reproduce and update here.

I look forward to, thank you

**Comment by youngtype** [comment]
> Ok thanks. I'll try to reproduce and update here.

To fix this error, it was necessary to install pyinstaller in path. I also had to install wixtoolset and write a path for it in the path so that the wix installer "C: \ Program Files (x86) \ WiX Toolset v3.11 \ bin" works. I wanted to ask if it is possible to use an exe installer here, like electron windows installer (squirrel) or electron builder nsis, so that the application starts immediately after the exe installation..?

**Comment by youngtype** [comment]
And one more question, 450 MB is quite a lot, is it possible to somehow reduce the final weight of the application?

**Comment by iPzard** [comment]
Oh I see. Yes, it looks like I have Wix Toolset installed, and I believe there was an option to add it to path during install. I'll need to update the readme with that, really appreciate the insight! 

For the final size, I did take measures to reduce the size, such as ensuring devDependencies  were not listed as dependencies in package.json, as well as a few other things. If any ideas come to mind, I'm happy to review them and see if they're feasible to implement.

**Comment by iPzard** [comment]
@youngtype FYI, just created this new ticket: https://github.com/iPzard/electron-react-python-template/issues/19
