### ISSUE TITLE
I get Error : can't not find "electron-devtools-installer" after building on windows and lunch dist\windows\app-win32-x64\app.exe

### ISSUE THREAD

**Issue by dassoukhi** [iPzard/electron-react-python-template#23]
Error : can't not find "electron-devtools-installer"
Require stack:
electron-react-python-template\dist\windows\app-win32-x...\main.js

can you help me please!
![Capture d’écran (16)_LI](https://user-images.githubusercontent.com/57576759/124982405-f2b90680-e036-11eb-8646-ae4799432773.jpg)

**Comment by iPzard** [comment]
Fixed in https://github.com/iPzard/electron-react-python-template/commit/66330eeab8a021199622c9e058a3524cc379b63a
