### ISSUE TITLE
Devtron issue

### ISSUE THREAD

**Issue by youngtype** [iPzard/electron-react-python-template#24]
![image](https://user-images.githubusercontent.com/79363260/125795087-ef37fbbd-8034-4e59-bfa3-3787ed7dedc0.png)
Devtron is not displayed

**Comment by iPzard** [comment]
It's been added to the extensions list in `main.js`, but haven't had time to get it installed and working properly just yet. Open to a PR if you get it added to your project!

**Comment by iPzard** [comment]
Looks like [Devtron is no longer maintained](https://github.com/electron-userland/devtron/issues/200) and does not work in the latest versions of Electron, which are used in this project. 

Closing the issue, removed references to Devtron in [this commit: https://github.com/iPzard/electron-react-python-template/commit/2342a8dbdd48b1c9b6b6984aea65d3f99cb3d90b
