### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by iPzard** [iPzard/electron-react-python-template#57]
**✨  Describe the feature**<br />
These packages are getting a bit old, they should be updated at some point. 

**Additional context**<br />

Might be a good solution for keeping the app up to date:
https://github.com/electron/update-electron-app

**Comment by sakujajp** [comment]
Thank you have shared this source code. During build:package:windows, python fails to run.

![image](https://user-images.githubusercontent.com/67476594/222191489-5f7b0a02-6579-481e-b1a3-ff5397cbc4d1.png)

**Comment by iPzard** [comment]
Thanks for sharing this @sakujajp! Can you add the details for this in a [bug report](https://github.com/iPzard/electron-react-python-template/issues/new?assignees=iPzard&labels=bug+%F0%9F%A6%9F&template=bug_report.md&title=)? There's some other helpful information it'll ask for there too.
