### ISSUE TITLE
Open new BrowserWindow on button click

### ISSUE THREAD

**Issue by msimoni18** [iPzard/electron-react-python-template#61]
**✨  Describe the feature**<br />
Load an html file in a new ``BrowserWindow`` on a button click. One example would be to open the documentation that is provided in the repo in a new window.

I haven't been able to figure out how to do it yet, but I can create a new branch outlining what I've tried.

**Comment by iPzard** [comment]
I can take a look into this. In case you're in a rush, have you tried the following? 

In [main.js](https://github.com/iPzard/electron-react-python-template/blob/c78c0d0578bf6e6b0c96564fe7291ca6871d29ae/main.js#L132)
```
// required first: npm install open
const open = require('open');

ipcMain.on('open-external-link', (_event, link) => {
  open(link)
});
```

In React
```
ipcRenderer.send('open-external-link', 'https://www.example.com');
```

**Comment by msimoni18** [comment]
Well, as expected, I figured it out shortly after opening this request and before reading your reply. It looks like I'm doing nearly same thing as you suggested. Thanks for the quick reply!

Here's what I did:

In ``services.js``, I added the following line to ``app``:

``docs: () => ipcRenderer.send("app-docs")``

In ``main.js``, I added the following:

```
const openDocs = () => {
  const docsWindow = new BrowserWindow({
    // parent: browserWindows.mainWindow,
    height: 300,
    width: 500
  });
  docsWindow.loadFile("docs/index.html");
  docsWindow.show();
};
```

With the other ipcRender events:
```
ipcMain.on("app-docs", (_event, _arg) => openDocs());
```

**Comment by iPzard** [comment]
That's usually how it goes lol, glad you got it figured out!
