### ISSUE TITLE
Support hot loading

### ISSUE THREAD

**Issue by ivanlori** [iPzard/electron-react-python-template#8]
App.js is not under /src folder but under /components and if I change something there, the application doesn't reload and update changes. I suppose I have to run the build to see updates but it's frustrating in dev mode.

**Comment by iPzard** [comment]
You're right, you'd have to rebuild React or use a web browser to work on just React stuff for hot loading.

But I agree, it would be an ideal feature to have, especially for dev mode. 

I'll look into incorporating this.

**Comment by hwjwill** [comment]
This might help https://medium.com/@devesu/how-to-build-a-react-based-electron-app-d0f27413f17f
Use concurrently and wait-on to start electron with react
and use electron-is-dev to check whether it's run in dev or build
`npm install electron-is-dev`
in main.js, instead of `mainWindow.loadFile`, change to
```
const isDev = require('electron-is-dev');
mainWindow.loadURL(isDev? 'http://localhost:3000' : `file://${path.join(__dirname, '../build/index.html')}`)
```

**Comment by iPzard** [comment]
Alright everyone, hot loading is here! The master branch has been updated to include this change. 

@hwjwill Thanks for the insight, this was very helpful to get the React side of things hot loading, then to get Flask hot loading as well along with the dynamic ports was a bit tricky, but was able to get it all sorted out. @ivanlori were absolutely right, much better with both React and Flask auto-updating on the fly in dev mode. Tested with a packaged build on Windows too and everything was working as expected. Feel free to open another issue if anything else is noticed!
